### PR TITLE
SelectDroplist Changes

### PR DESCRIPTION
**Pull request by HasaanSaeed**
dropboxborderradius
dropboxbordercolor

### CODE REVIEW

**Comment by sharmajatin1997** [comment]
@HasaanSaeed Thanks for update

**Comment by HasaanSaeed** [comment]
> @HasaanSaeed Thanks for update

My Pleasure Brother .
Thanks for your Support

**Comment by HasaanSaeed** [comment]
Bro  Can you Also Update it on Pub.dev.. 😊

**Comment by sharmajatin1997** [comment]
Yeah sure bro currently working on other functionality after that i will
update on pub dev

**Comment by HasaanSaeed** [comment]
Okay Thank you so much ♥️

**Comment by sharmajatin1997** [comment]
You're welcome! Buddy😇

**Pull request merged**
