### PR TITLE
Update select_drop_list.dart

### PR DESCRIPTION
**Pull request by HasaanSaeed**

### CODE REVIEW

**Comment by HasaanSaeed** [comment]
See if it ok to you

**Comment by sharmajatin1997** [comment]
@HasaanSaeed What Changes You have Done Please Explain. So i will check and update

**Comment by HasaanSaeed** [comment]
I have Added Custom BorderRadius to the Dropdown Box, And also The border
color to dropdownbox.
I named them (dropBoxborderRadius and dropboxborderColor)
Added them to Size Transition widget in *SelectDroplist* Only.

**Comment by sharmajatin1997** [comment]
@HasaanSaeed bro i can't See any new Changes in your commit pls check your commit code.

**Comment by HasaanSaeed** [comment]
Brother i think there was some issue on my side.
Check now i made a pull request again

**Pull request closed without merging**
